name : "Sample Git hub Actions"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  defaults:
    run:
      shell: bash

steps:
  # Step 1: Checkout the repository
  - name: Checkout Code
    uses: actions/checkout@v4