name: "Sample GitHub Actions"

on:
  push:
    branches:
      - main  # Replace with your branch name

permissions:
  contents: read

jobs:
  defaults:
    runs-on: ubuntu-latest  # ✅ This specifies the runner (required)
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Run a script
        run: echo "Hello, GitHub Actions!"